### ISSUE TITLE
What if I want to enable the user to see each other's review

### ISSUE THREAD

**Issue by ghost** [jadianes/winerama-recommender-tutorial#4]
I want to enable the users can see each other's reviews and they can visit other's profile and also comment on the others' review. Could you please tell me how to modify the models and views? Thank you very much.

**Comment by jadianes** [comment]
Hi rylanchiu,

A user can see other users review by navigating to its user profile (e.g. clicking on a user name in a wine review). Comments are not implemented. That is a completely different story!
