### ISSUE TITLE
unsupported operand type(s) for /: 'map' and 'int'

### ISSUE THREAD

**Issue by Puriney** [jadianes/winerama-recommender-tutorial#9]
Great demo for Django.

I ran the demo and came across with an error: `unsupported operand type(s) for /: 'map' and 'int'` which is related to these two lines: https://github.com/jadianes/winerama-recommender-tutorial/blob/4cbfd04137b37d988f707509702ccbc49122d97f/winerama/reviews/models.py#L10-L11

It is for calculating the avarage rating by using numpy. But numpy is not in favor of `map`. So a possible solution is to turn the map object to a list.

```
np.mean(list(all_ratings))
```

Just in case that anyone out there happened to meet with the problem.

**Comment by sandeep135** [comment]
https://stackoverflow.com/questions/44928441/unsupported-operand-types-for-map-and-int

see this will definitely help
